### PR TITLE
Rhel 6 rollbacks

### PR DESCRIPTION
**Pull request by mfranczy**
(pstodulk) short description
The purpose of this solution is to provide rollbacks for (x86_64)  systems using the LVM snapshots. There are added new options to achieve that:
- --snapshot-root-lv
-  --snapshot-lv

Where the first one is used to create snapshot of the root lvm partition, second one is used to create snapshot of the non-root lvm partition (can be used multiple times). rhelup will create several entries inside the grub.conf, so you would do rollback when you boot to the *RHEL 6 Snapshot* entry and then run `redhat-upgrade-tool --system-restore` then reboot and boot back to the original RHEL 6 system. Or in case you upgraded the system (but havn't migrated to grub2 yet), you can run
```
cd /boot && python -m rollback.system_restore
```
that will automatically reboot the system as well.

After you boot to original partition, run the `redhat-upgrade-tool --clean` command to clean some artifacts from the upgrade inside the /boot/ partition. The man pages and  help are modified as well, for more info.

### CODE REVIEW

**Comment by pirat89** [comment]
-- test --

**Review by pirat89 — DISMISSED** [review]
test

**Review by artmello — APPROVED** [review]
LGTM

**Comment by pirat89** [comment]
Merging this PR as we plan to do additional changes in separate PRs because this one is pretty big already.

**Pull request merged**
